<?php
return[

    'categories'=>[
        'Choose category' ,
        'Apartments & Duplex for Sale' ,
        'Apartments & Duplex for Rent' ,
        'Villas For Sale' ,
        'Villas For Rent' ,
        'Vacation Homes for Sale' ,
        'Vacation Homes for Rent' ,
        'Commercial for Sale' ,
        'Commercial for Rent' ,
        'Buildings & Lands'
    ],

    'types' =>[
        'Choose type' ,
        'Stand Alone Villa' ,
        'Town House' ,
        'Twin House'
    ],

    'amenities' => [
        'Choose one or more of these amenities' ,
        'Balcony' , 'Built in Kitchen Appliances' , 'Private Garden' , 'Central A/C & heating' ,
        'Security' , 'Covered Parking' , 'Maids Room' , 'Pets Allowed' , 'Pool' , 'Electricity Meter' ,
        'Water Meter' , 'Natural Gas' , 'Landline' , 'Elevator'
    ],

    'bedrooms' => [
        'Choose one of these' ,  '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , '10' , '+10'
    ],

    'bathrooms' => [
        'Choose one of these' , '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , '10' , '+10'
    ],

    'levels' => [
        'Choose one of these' , 'Ground' , '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , '10' , '+10' , 'Highest'
    ],

    'furnished' => [
        'Choose one of these' , 'yes' , 'no'
    ],

    'compounds' => [
        'Choose compound' ,
        '90 Avenue',
        '2020 Compound',
        'ABHA',
        'ALBA',
        'AZAD',
        'Abu Al-Hool',
        'Aeon',
        'Agora',
        'Akoya',
        'Al-Jazeera',
        'Al Burouj',
        'Al Diyar',
        'Al Hayah',
        'Al Maqsad',
        'Al Maram Landmark',
        'Al Nasayem',
        'Al Rabwa',
        'Al Riyadh Secon',
        'Al Solaimaneyah Golf City',
        'Al Yasmine',
        'Alex West',
        'Alico city',
        'Allegria',
        'Alma',
        'Amorada',
        'Anakaji',
        'Andalus',
        'Arabella Park',
        'Arabella Village',
        'Arabia',
        'Arabia Gate',
        'Arena City Towers',
        'Aria',
        'Armonia',
        'Art City',
        'Asala',
        'Asayla',
        'Ashgar City',
        'Ashrafeya',
        'Asmarat Heights',
        'Astoria Park',
        'Aswar',
        'Atika',
        'Atrio',
        'Avaris',
        'Azalea',
        'Azzar',
        'Badya Palm Hills',
        'Baet El Masria',
        'Bamboo Palm Hills',
        'Baron City',
        'Baroque',
        'Bavaria Town',
        'Bedaya',
        'Beit Al Watan',
        'Bel Air - Sodic',
        'Bellagio',
        'Belle Vie',
        'Beta Gardens',
        'Beta Greens',
        'Beverly Hills',
        'Bienestar',
        'Bloomfields',
        'Blue Vert',
        'Botanica',
        'Bright City',
        'Cairo Festival City',
        'Cairo Gate',
        'Cairo Town',
        'Capital Gardens',
        'Capital Gate',
        'Capital Heights 2',
        'Casa Verde',
        'Castle Landmark',
        'Catalan',
        'Catalya',
        'Celia',
        'Century City',
        'City One',
        'City Oval',
        'Cleo East',
        'Cleopatra Palace',
        'Cleopatra Square',
        'Comex Gardens',
        'Concord Gardens',
        'Concordia',
        'Continental Gardens',
        'Copen Gate',
        'County',
        'Creek Park',
        'Creek Town',
        'Cresta Bella Hills',
        'Crystal Plaza',
        'Dar Misr',
        'De Joya',
        'Degla Gardens',
        'Degla Landmark',
        'Degla Palms',
        'Degla Towers',
        'Degla View',
        'Dimora',
        'Diplomats',
        'District 5 Compound',
        'Divina Gardens',
        'Dreamland',
        'Dyar',
        'EL Patio 2',
        'EL Patio 3',
        'EL Patio 4',
        'EL Patio 5',
        'EL Patio 6',
        'EL Patio 7',
        'EL Patio Casa',
        'EL Patio ORO',
        'EL Patio Prime',
        'East Cairo',
        'Eastown',
        'Easy Life',
        'Eclat',
        'Eco West',
        'El Ashgar District',
        'El Aziza',
        'El Karma',
        'El Karma 2',
        'El Karma 3',
        'El Karma 4',
        'El Khamayel',
        'El Ofok El Gadid',
        'El Patio',
        'El Reef El Orouby',
        'El Shorouk Springs',
        'Emerald Park',
        'Entrada',
        'Eshraqa',
        'Etapa',
        'Ethmar Compound',
        'Etlalah',
        'Etoile de Ville',
        'Evergreen',
        'Family City',
        'Fifth Square',
        'Fleur De Ville',
        'Florenta',
        'Floria',
        'Flowers Park',
        'Forty West - Sodic',
        'Fountain Park',
        'Future Gate',
        'GCR',
        'GCR Golf City',
        'Galleria',
        'Galleria Moon Valley',
        'Garana',
        'Garden Hills',
        'Gardenia',
        'Gardenia Springs',
        'Gharb Golf',
        'Gharb Golf & Extension',
        'Gladios Garden',
        'Go Heliopolis',
        'Golden Heights',
        'Golden Heights 2',
        'Golden Park',
        'Golden Yard',
        'Grand Gate',
        'Grand Heights',
        'Grand Residence',
        'Granda',
        'Green 4',
        'Green Avenue',
        'Green Plaza 1',
        'Green Square',
        'Green Yard',
        'Greenland',
        'Greens',
        'Guezira 1',
        'Hadaba',
        'Haletown',
        'Haptown',
        'Haram City',
        'Hayah Residence',
        'Hayat Heights',
        'Hayati Residence',
        'Heliopolis Residence',
        'Hexa',
        'High City',
        'Highland Park',
        'Hyde Park New Cairo',
        'IL Bosco',
        'IL Bosco City',
        'Il Mondo',
        'Isola',
        'Italian Square',
        'Ivory Hill',
        'Ivy Residence',
        'Jada',
        'Jasmine City',
        'Jasper',
        'Jayd',
        'Jedar',
        'Jeera',
        'Jewar',
        'Jewels',
        'Jodran',
        'Joulz',
        'Jubail',
        'Kanarya',
        'Karma Residence',
        'Karmell',
        'Katameya Breeze',
        'Katameya Creeks',
        'Katameya Dunes',
        'Katameya Heights',
        'Katameya Hills',
        'Katameya Plaza',
        'Kattameya Gardens',
        'Kattameya Gate',
        'Kattameya Palms',
        'Kattameya Residence',
        'Kayan',
        'Keeva',
        'Kenz',
        'Kings range',
        'Korba Heights',
        'La Capital',
        'La Fontaine Province',
        'La Mirada',
        'La Nouva Vista',
        'La Rose',
        'La Terra',
        'La Verde',
        'La Verde Casette',
        'La Vida',
        'La Vista City',
        'Lac Ville',
        'Ladera',
        'Lake Side',
        'Lake View',
        'Lake West',
        'Lakefront',
        'Lake view Residence',
        'Lavande',
        'Lavida',
        'Layan',
        'Le Ciel',
        'Le Jardin',
        'Le Jour',
        'Leena Springs',
        'Legenda',
        'Leila',
        'Lereve',
        'Les Rois',
        'Liberty Village',
        'Life Garden',
        'Life Point',
        'Life View',
        'Light City',
        'L’Avenir',
        'Maadi Dunes',
        'Maadi Gardens',
        'Maadi Grand City',
        'Maadi V',
        'Maadi Valley',
        'Maadi View',
        'Madinaty',
        'Mahika',
        'Majorelle',
        'Makany',
        'Malaga',
        'Marina City',
        'Marvel City',
        'Mashareq',
        'Maxim Country Club',
        'May Fair',
        'Meadows Park',
        'Medallion',
        'Mena City Central',
        'Mena Garden City',
        'Mena Residence',
        'Menorca',
        'Merida',
        'Midtown',
        'Midtown Condo',
        'Midtown Sky',
        'Midtown Solo',
        'Mirage City',
        'Mirage Residence',
        'Mivida',
        'Monte Napoleon',
        'Moon City',
        'Moon Garden',
        'Moon Hillls',
        'Moon Land',
        'Moon Valley',
        'Mountain Plaza',
        'Mountain View - Giza Plateau',
        'Mountain View - October Park',
        'Mountain View 1',
        'Mountain View 2',
        'Mountain View 3',
        'Mountain View Chillout Park',
        'Mountain View Executive',
        'Mountain View Hyde Park',
        'Mountain View iCity',
        'Murooj',
        'Nakheel',
        'Neopolis',
        'Nest Cairo',
        'New Giza',
        'Next Point',
        'Noor City',
        'Not in Compound',
        'OIA',
        'O West',
        'October Plaza Sodic',
        'Odyssia',
        'One 16',
        'One Kattameya',
        'One Ninety',
        'Opera City',
        'Operetta Greens',
        'Oriana',
        'Ourika',
        'Palm Hills Alexandria',
        'Palm Hills Katameya',
        'Palm Hills Katameya Extension',
        'Palm Hills New Cairo',
        'Palm Parks',
        'Palm Valley',
        'Palm View',
        'Palm hills golf extension',
        'Palm hills golf views',
        'Paradise',
        'Park Lane',
        'Park View',
        'Point 90',
        'Porto Cairo',
        'Porto Heliopolis',
        'Porto New Cairo',
        'Porto October',
        'Princess',
        'Promenade Maadi',
        'Promenade New Cairo',
        'Pukka',
        'Pyramids Heights',
        'Pyramids Hills',
        'Pyramids Walk',
        'Quattro',
        'Rawdat Zayed',
        'Rayhanah Avenue',
        'Rayhanah Plaza',
        'Rayhanah Residence',
        'Rayos',
        'Reem Residence',
        'Regents Park',
        'Rehab City',
        'Rehab October City',
        'Residence 8',
        'Reve',
        'Rhodes',
        'Rich Mont',
        'Ritage',
        'Rivan',
        'River Walk',
        'Riviera Heights',
        'Rock Eden',
        'Rock Vera',
        'Rock Ville',
        'Roses',
        'Royal City',
        'Royal Lagoon',
        'Royal Maxim',
        'Royal Meadows',
        'Safwa Dream',
        'Sama',
        'Sarai',
        'Sarayat El Kattameya',
        'Scarta',
        'Scenario',
        'Scene 7',
        'Seabelle',
        'Seasons',
        'Sedra',
        'Selena',
        'Sephora Heights',
        'Serena Heights',
        'Serrano',
        'Sheraton Residence',
        'Shorouk Gardens',
        'Silva ',
        'Six West',
        'Sky AD',
        'Sky Capital',
        'Sky Capital View',
        'Sky Condos Sodic',
        'Sky View Premier',
        'Skyline',
        'Smart Life',
        'Smart Life Town',
        'Sodic East',
        'Sodic Westown',
        'Spanish District',
        'Stau',
        'Stella Compounds',
        'Stella New Cairo',
        'Stella Park',
        'Stone Park',
        'Stone Residence',
        'Sueno',
        'Sukoon',
        'Sun Capital',
        'Sun City',
        'Sun City Gardens',
        'Sun Gate',
        'Sun Rise',
        'Swan Lake',
        'TRUE Gate',
        'Tag Sultan',
        'Taj City',
        'Tala',
        'Tamr Henna',
        'Tawny',
        'Terrace Smouha',
        'The Address East',
        'The Axis',
        'The Brooks',
        'The Canyon',
        'The Capital Way',
        'The City',
        'The Core',
        'The Crown',
        'The Curve',
        'The Estates',
        'The Icon Residence',
        'The Key',
        'The Loft',
        'The MarQ',
        'The Pearl',
        'The Ridge',
        'The Square',
        'The Strip - Sodic',
        'The Strip II - Sodic',
        'The View',
        'The Village',
        'The Walk Trenta',
        'The Water Marq',
        'The Waterway Compound',
        'Tiara Residence',
        'Tiba Gardens',
        'Tiba Smart City',
        'Tijan',
        'Town Gate',
        'Trevi',
        'Trillium',
        'Trio Gardens',
        'TRUE',
        'Uphill Residence',
        'Upside Maadi',
        'Uptown Cairo',
        'Upville',
        'VGK',
        'Valeria Maadi',
        'Valore Sheraton',
        'Village Avenue',
        'Village Gardens Katameya',
        'Village Gate',
        'Village West',
        'Villar Residence',
        'Villette',
        'Villino',
        'Vinci',
        'Vivienda',
        'Wahet El Ryhan',
        'West Gate',
        'White Sand',
        'Woodville',
        'Yaru',
        'ZED Towers',
        'Zahret El Tagamo',
        'Zahwa',
        'Zahya',
        'Zavani',
        'Zayed 2000',
        'Zayed Dunes',
        'Zayed Greens',
        'Zayed Regency',
        'Zed East',
        'Zizinia El Mostakbal',
        'Zizinia Gardens',

    ],

    'deliveryDates' => [
        'Choose delivery date' , 'Ready to buy' , 'soon' , 'within 6 months' , '2022' , '2023'
    ],

    'deliveryTerms' => [
        'Choose delivery terms' ,
        'core & Shall' ,
        'Finished' ,
        'Not Finished' ,
        'Semi Finished'
    ]








    ];
